# This workflow checks that all files and directories are named using snake_case

name: CI

on:
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  check-names:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Check file and directory names
        run: |
          WRONG_NAMES="$(find . | grep -v -e '/\.' -e '.*\.import' -e '.*\.md' | egrep -v '^[\./_[:lower:]0-9]+$')"
          if [ "$WRONG_NAMES" ] ; then
             echo "::error::All files and directories should be named using snake_case"
             echo "$WRONG_NAMES"
             exit 1
          fi
